//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _111zal2
{
    using System;
    using System.Collections.Generic;
    
    public partial class karlitos_products
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string SerialNumber { get; set; }
        public string Color { get; set; }
        public Nullable<double> Price { get; set; }
        public string Type { get; set; }
        public Nullable<long> QTY { get; set; }
    }
}
